version: '2'
services:
  jenkins:
    build: .
    image: 'jenkins_withmaven'
    container_name: 'jenkins'
    ports:
      - '8081:8080'
      - '8443:8443'
      - '50000:50000'
    environment:
      - PLUGINS_FORCE_UPGRADE=true
    volumes:
      - '~/tmp/docker/jenkins/home:/var/jenkins_home'
      - '~/tmp/docker/maven/home:/usr/jenkins/.m2'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - 'local'
  registry:
    restart: always
    image: 'registry:2'
    container_name: 'registry-core'
    ports:
      - '5000:5000'
    environment:
      - 'REGISTRY_HTTP_ADDR=registry-core:5000'
      - 'REGISTRY_HTTP_RELATIVEURLS=true'
    volumes:
      - '~/tmp/docker/doker-registry/data:/var/lib/registry'
    networks:
      - 'local'
  registry-web:
    restart: always
    image: 'hyper/docker-registry-web'
    container_name: 'registry-web'
    environment:
      - 'REGISTRY_NAME=registry-core:5000'
      - 'REGISTRY_URL=http://registry-core:5000/v2'
    ports:
      - '8082:8080'
    networks:
      - 'local'
networks:
  local: