version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8081:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
volumes:
  jenkins_data:
    driver: local