version: '2'
services:
  jenkins:
    build: .
    image: 'jenkins_withmaven'
    ports:
      - '8081:8080'
      - '443:8443'
      - '50000:50000'
    environment:
      - PLUGINS_FORCE_UPGRADE=true
    volumes:
      - '~/tmp/docker/jenkins/home:/var/jenkins_home'
      - '~/tmp/docker/maven/home:/usr/jenkins/.m2'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - 'local_build_env'
  registry:
    restart: always
    image: 'registry:2'
    ports:
      - '5000:5000'
    volumes:
      - '~/tmp/docker/doker-registry/data:/var/lib/registry'
      - '~/tmp/docker/doker-registry/certs:/certs'
      - '~/tmp/docker/doker-registry/auth:/auth'
    networks:
      - 'local_build_env'
networks:
  local_build_env: